<img src = "images/Logo.png" width = 220, align = "left">

<h1 align=center><font size = 6><span style="color:blue">Brief Introduction to NumPy</span></font></h1>
<h2 align=center><font size = 5>Lab Exercise for Appendix B</font></h2>
<h3 align=center><font size = 4><b>Advanced Machine Learning Made Easy<br></b><small>From Theory to Practice with NumPy and scikit-learn<br><i>Volume 1: Generalized Linear Models</i></font></h3>

## Introduction

NumPy, short for Numerical Python, is the fundamental package required for highperformance
scientific computing and data analysis. This appendix aims to provide a quick introduction to the NumPy library and the corresponding mathematical formulas and namings used throughout the book. It should not be seen as a complete reference.

**Note:** *You should perform this lab exercise while reading the Annex B of the book, where explanatory pictures and useful links to videos are also included.*

### Table of contents
1. [Introduction](#Intro)
2. [Scalars](#Scalars)
3. [Vectors](#Vectors)
4. [Matrices](#Matrices)
5. [Array Manipulations](#Array)

## 1. Introduction <a name="Intro"></a>

Before using the NumPy library, it must be imported to your environment. With the following command, we will import NumPy with 'np' alias.

In [1]:
import numpy as np

Unlike a Python list, a NumPy array is a contiguous block of memory, thus, it is more efficient and faster than lists. That requires that all of the elements of an array must be the same type.

Let's create an array with one element containing the constant value of 1.

In [2]:
x=np.array(1)
x

array(1)

The total number of elements in the array:

In [3]:
x.size

1

Number of bytes occupied in the memory by one element:

In [4]:
x.itemsize

4

The total number of bytes occupied by the array (not including the array header) is the product of the two numbers above.

The type of the array is:

In [5]:
x.dtype

dtype('int32')

## 2. Scalars <a name="Scalars"></a>

From the mathematical point of view, a Python object corresponds to a scalar (denoted with small italic letters in the book, like $\mathit a,\mathit b,\mathit c,\dots,\mathit x,\mathit y,\mathit z,\dots$). Let's assign to x the constant value of 1 and then check the result.

In [6]:
x=1
x

1

In NumPy terminology, a scalar represents a ndarray of rank 0 (or dimension 0).<br>
Convert the scalar to a NumPy array.

In [7]:
x=np.array(x)
x

array(1)

Check the dimension of $x$ (it should be zero).

In [8]:
x.ndim

0

Check the shape of $x$ (it should be an empty tuple).

In [9]:
x.shape

()

Cast the 0 dimensional array to scalar value (Python integer).

In [10]:
x=int(x)
x

1

## 3. Vectors <a name="Vectors"></a>

A vector, denoted by small bold letters in the book, like $\mathbf a,\mathbf b,\mathbf c, \dots,\mathbf x,\mathbf y,\mathbf z, \dots$, represents an array containing multiple scalar values ordered in a single column.

**Note:** *By mathematical definition, a vector always represents a column vector, which has N rows and one column.*

### Vector initialization

There are several ways to create and initialize a vector in NumPy. The simplest way is to initialize a vector to have all their values set to either zero or one using *zeros* method

In [11]:
x_=np.zeros(3)
x_

array([0., 0., 0.])

respective *ones* methods

In [12]:
x_=np.ones(5)
x_

array([1., 1., 1., 1., 1.])

The third option is to provide a number to fill the vector elements with *full* method.

In [13]:
x_=np.full(5,5)
x_

array([5, 5, 5, 5, 5])

You may check the dimension of the vector.

In [14]:
x_.ndim

1

and the shape of it

In [15]:
x_.shape

(5,)

The transpose of a (column) vector is a row vector (and vice verso, where the values are ordered in a single row instead of a single column. You may use either the *transpose* method or the *T* unary operator.

In [16]:
x_.transpose()

array([5, 5, 5, 5, 5])

There is a problem though, the shape is the same.

In [17]:
x_.T

array([5, 5, 5, 5, 5])

You may check this with the *shape* attribute.

In [18]:
x_.T.shape

(5,)

For this reason we need to define our vector as two dimansional NumPy array by adding a new axis with *np.newaxis*:

In [19]:
x_=x_[:,np.newaxis]
x_

array([[5],
       [5],
       [5],
       [5],
       [5]])

Or define the shape with two elements in the tuple for the *zeros*, *ones*, *full* method. Then you may ckeck the shape

In [20]:
x_=np.full((5,1),5)
x_.shape

(5, 1)

and dimension

In [21]:
x_.ndim

2

You can state only the number of elements, but add a new axis as the first one

In [22]:
x_=np.ones(4)[np.newaxis]
x_

array([[1., 1., 1., 1.]])

and check the shape

In [23]:
x_.shape

(1, 4)

Now, we may check the transpose of the vector

In [24]:
x_.T.shape

(4, 1)

The numbers in the tuple have been exchanged, meaning that we have 4 rows and one column (previously we had one row and 4 columns).

In [25]:
x_.T

array([[1.],
       [1.],
       [1.],
       [1.]])

We may create a vector (numPy array) from a nested list or nested tuple with *array* method.

In [26]:
x_=np.array([[1,2,3,4]])
x_

array([[1, 2, 3, 4]])

Be aware about the number of squared brackets in the above code.

In [27]:
x_=np.array((1,2,3,4))[:,np.newaxis]
x_

array([[1],
       [2],
       [3],
       [4]])

Numpy *arange* is useful when you want to create a NumPy array, having a range of elements spaced out over a specified interval between *start* and *stop* values with a given *step* size. By default, the start is zero, and the step size is 1.

In [28]:
x_=np.arange(4)
x_

array([0, 1, 2, 3])

Both start and stop specified

In [29]:
x_=np.arange(1,5)
x_

array([1, 2, 3, 4])

Start, stop, and step is given.

In [30]:
x_=np.arange(1,7,2)
x_

array([1, 3, 5])

NumPy *linspace* method is used to create a NumPy array whose elements are equally spaced between the *start* and *end*.

In [31]:
x_=np.linspace(1,50,dtype=int)
x_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

or you can create as a column vector

In [32]:
x_=np.linspace(1,4,4,dtype=int)[:,np.newaxis]
x_

array([[1],
       [2],
       [3],
       [4]])

You may also create a logarithmic scale.

In [33]:
y_=np.logspace(1,4,4)[:,np.newaxis]
y_

array([[   10.],
       [  100.],
       [ 1000.],
       [10000.]])

We can check the type of the data stored in the array.

In [34]:
y_.dtype

dtype('float64')

The Python built-in *len* method can be also used which provides the number of elements of a column vector.

In [35]:
len(y_)

4

However, the *len* method always gives the size of the first axis only, so a row vector will have length of 1.

In [36]:
len(y_.T)

1

You may initializing vectors (NumPy) arrays with random values.<br>
Single sample from a uniform distribution (setting seed, the same random samples you shall get every time).

In [37]:
np.random.seed(1)
y=np.random.randint(2)
y

1

Rolling dice ten times

In [38]:
y_=np.random.randint(1,7,10)
y_

array([4, 5, 1, 2, 4, 6, 1, 1, 2, 5])

or flipping a coin fifteen times

In [39]:
y_=np.random.randint(0,2,15)
y_

array([1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0])

Single sample for a standard normal distribution:

In [40]:
y=np.random.randn()
y

1.462107937044974

Three random samples from standard normal distribution:

In [41]:
y_=np.random.randn(3)
y_

array([-2.06014071, -0.3224172 , -0.38405435])

Three random samples from $\mathcal N(2,3)$:

In [42]:
y_=3*np.random.randn(3)+2
y_

array([ 5.40130833, -1.2996738 ,  1.48271538])

You may create a NumPy array without initialization with *empty* method (filling the values can be done at a later stage).

In [43]:
x_=np.empty((2,1))

### Accessing Vector Elements

Using only the row index the whole row is selected resulting in an array with only one element.

In [44]:
x_=np.array([1,2,3,4])[:,np.newaxis]
x_[(1)]

array([2])

Indexing the row only will result in an array with one element.

In [45]:
x_[1]

array([2])

When indexing both axis a scalar is returned. 

In [46]:
x_[(1,0)]

2

Omitting the brackets

In [47]:
x_[1,0]

2

The last element can be accessed using $-1$ indexing:

In [48]:
x_[-1,0]

4

and the element before last with $-2$ indexing:

In [49]:
 x_[-2,0]

3

Selecting all but the last element from the vector

In [50]:
x_[0:3,0]

array([1, 2, 3])

Selecting from the 2nd to the last but one elements (the two middle elements).

In [51]:
x_[1:-1,0]

array([2, 3])

Selecting every second element.

In [52]:
x_[0:4:2,0]

array([1, 3])

Selecting all but the last element.

In [53]:
x_[:3,0]

array([1, 2, 3])

Selecting all but the first element.

In [54]:
x_[1:,0]

array([2, 3, 4])

Selecting all elements (from the first axis):

In [55]:
x_[:,0]

array([1, 2, 3, 4])

Choosing $-1$ for the step size, the elements are selected in reverse order.

In [56]:
x_[::-1,0]

array([4, 3, 2, 1])

With one colon, select all but last

In [57]:
x_[:-1,0]

array([1, 2, 3])

If we want the result to be a 2 dimensional ndarray then *newaxis* shall be added at the end.

In [58]:
x_[::-1,0][:,np.newaxis]

array([[4],
       [3],
       [2],
       [1]])

Indexing can be also done using a list. In such a case, the elements can be selected in any order and can be selected more than once.

In [59]:
x_[[3,1,2,1,0]]

array([[4],
       [2],
       [3],
       [2],
       [1]])

Selecting the first two elements in the same order, similar to slicing.

In [60]:
x_[[0,1]]

array([[1],
       [2]])

Indexing can be also done with another vector:

In [61]:
y_=np.array([0,2])
x_[y_]

array([[1],
       [3]])

If the second axis is specified, the returned value will be 1-dimensional.

In [62]:
x_[y_,0]

array([1, 3])

When indexing is done with a 2-dimensional array, the second axis shall be set to 0, otherwise, a 3-dimensional array will be returned.

In [63]:
x_=np.array([1,2,3,4,5,6])[:,np.newaxis]
y_=np.array([[1],[3]])
x_[y_].shape

(2, 1, 1)

Setting the 2nd axis

In [64]:
x_[y_,0]

array([[2],
       [4]])

When indexing an element you get a view on the element, so you can alter the content of the vector.

In [65]:
x_[:2,0]=0
x_

array([[0],
       [0],
       [3],
       [4],
       [5],
       [6]])

If you want to get a copy, instead of view, use the *copy* method.

In [66]:
x_.copy()[:]=4
x_

array([[0],
       [0],
       [3],
       [4],
       [5],
       [6]])

Changing the copy does not alter the original array.<br>
We may also use Boolean arrays to create a view (select elements). Let's create an array with numbers from 1 to 6, respective a Boolean array from this (True value for even numbers, and False value for odd numbers.

In [67]:
x_=np.arange(1,7)[:,np.newaxis]
x_%2==0

array([[False],
       [ True],
       [False],
       [ True],
       [False],
       [ True]])

Then select the even numbers from the array.

In [68]:
x_[x_%2==0][:,np.newaxis]

array([[2],
       [4],
       [6]])

More complex Boolean expressions can be applied, like making an AND between the two Boolean arrays resulted from *x_!=2* and *x_!=3*.

In [69]:
x_[np.logical_and(x_!=2,x_!=3)]

array([1, 4, 5, 6])

Or we can use a boolean expression by using the *logical_or* to select the elements which are either even number or greater than 2.

In [70]:
x_[np.logical_or(x_>2,x_%2==0)]
#x_>2

array([2, 3, 4, 5, 6])

In machine learning, you should check if all observations have a valid value. The *isnan* method returns True for the element which is Not A Number (NaN).

In [71]:
np.isnan(x_)

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False]])

You may create a single return value to check if all values are valid.

In [72]:
np.logical_not(np.isnan(x_)).all()

True

You may also check if any number is greater than 6.

In [73]:
(x_>6).any()

False

Compare the vector with its inversely ordered counterpart.

In [74]:
y_=x_[::-1]
np.greater(x_,y_)

array([[False],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

Sometimes you may want to iterate over the elements of the array. You may do that with *nditer* method.

In [75]:
for i in np.nditer(x_):
    print(i, end=' ')
print()

1 2 3 4 5 6 


### Adding and Removing Elements

There are cases when new elements need to be added to your vector (array).

For example, you may append one single element (scalar) to the end of the vector 'x_'.

In [76]:
x_=np.arange(1,5)[:,np.newaxis]
np.append(x_,5)

array([1, 2, 3, 4, 5])

Or append to the vector 'x_' another vector 'y_'.

In [77]:
y_=np.array([[5],[6]])
x_=np.append(x_,y_)[:,np.newaxis]
x_

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Sometimes, you may also want to specify the location of the insertion of a single element:

In [78]:
np.insert(x_,3,-14)

array([  1,   2,   3, -14,   4,   5,   6])

or the location of a list of elements (another vector):

In [79]:
v_=np.array([[-14],[-7]])
np.insert(x_,3,v_[:,0])

array([  1,   2,   3, -14,  -7,   4,   5,   6])

You may want to insert a single element into multiple locations:

In [80]:
i_=np.array([[1],[3]])
np.insert(x_,i_[:,0],-14)

array([  1, -14,   2,   3, -14,   4,   5,   6])

or specify the location of each vector element inserted (the dimension of the vector of values and indexes must match):

In [81]:
np.insert(x_,i_[:,0],v_[:,0])[:,np.newaxis]

array([[  1],
       [-14],
       [  2],
       [  3],
       [ -7],
       [  4],
       [  5],
       [  6]])

If there are observations with invalid values, you may want to remove them.<br>
For example, create a vector with invalid entried (NaN - Not a Number)

In [82]:
y_=np.array([1,np.nan,3,np.nan],ndmin=2).T
y_

array([[ 1.],
       [nan],
       [ 3.],
       [nan]])

then check for NaN values in the array.

In [83]:
np.isnan(y_)

array([[False],
       [ True],
       [False],
       [ True]])

Then using the Boolean array you create the array of indexes

In [84]:
idx_=np.nonzero(np.isnan(y_))[0]
idx_

array([1, 3], dtype=int64)

and delete the invalid observations

In [85]:
y_=np.delete(y_,idx_)
y_

array([1., 3.])

This can be done in one line of code providing the Boolean array directly to the *delete* method.

In [86]:
y_=np.array([1,np.nan,3,np.nan],ndmin=2).T
y_=np.delete(y_,np.isnan(y_)[:,0])
y_

array([1., 3.])

We can use the result as an array of indexes to remove elements from another vector.

In [87]:
np.delete(x_,y_.astype(int))[:,np.newaxis]

array([[1],
       [3],
       [5],
       [6]])

### Operations on Vectors

Every arithmetical operations between scalars can be applied to vectors element-wise, too.<br>
For example, let's create two vectors from nested lists, and add them together with *add* method.

In [88]:
x_=np.array([[1],[3],[5],[7]])
y_=np.array([[2],[4],[6],[8]])
np.add(x_,y_)

array([[ 3],
       [ 7],
       [11],
       [15]])

or with the '+' operator (resembles the mathematical formula: $\mathbf x+\mathbf y$):

In [89]:
x_+y_

array([[ 3],
       [ 7],
       [11],
       [15]])

Arithmetic operation is also possible between a vector and a scalar with the broadcast. NumPy, before executing the operation between the array and scalar, "broadcasts" the values of the scalar into an array having the same shape as the original array and then executes the arithmetic operation between the vectors element-wise.<br>
The following code resembles the mathematical formula: $\mathbf x-x$

In [90]:
x_-x

array([[0],
       [2],
       [4],
       [6]])

Here is another example:

In [91]:
x_=np.array([[1],[2],[3],[4]])
x=5
x_+x

array([[6],
       [7],
       [8],
       [9]])

The element-wise operations are done on a copy of x_, x_ is not altered.

In [92]:
x_

array([[1],
       [2],
       [3],
       [4]])

Vector element-wise multiplication with itself:

In [93]:
x_=np.array([[1],[2]])
x_*x_

array([[1],
       [4]])

Broadcasting is done even for cases what are not defined mathematically.<br>
Vector element-wise multiplication with its transpose:

In [94]:
x_*x_.T

array([[1, 2],
       [2, 4]])

and in reverse order

In [95]:
x_.T*x_

array([[1, 2],
       [2, 4]])

Element-wise multiplication between vectors of different size:

In [96]:
x_=np.array([1,2,3,4],ndmin=2).T
y_=np.array([7,8,9],ndmin=2).T
x_.T*y_

array([[ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36]])

and with reverse order:

In [97]:
y_.T*x_

array([[ 7,  8,  9],
       [14, 16, 18],
       [21, 24, 27],
       [28, 32, 36]])

**Note:** *The above multiplications should not be confused with the outer product of vectors.*

If you want your code to execute faster and consume less memory use $+=, -=, *=,/=$ which act in place to modify the existing array rather than create a new one by copying the existing array. But with $-=$ operation the vector is altered.

In [98]:
x_-=x
x_

array([[-4],
       [-3],
       [-2],
       [-1]])

Be aware, that if you add a scalar float to an integer array, the copy will be up-cast before making the element-wise arithmetic operation.

In [99]:
x_+10.0

array([[6.],
       [7.],
       [8.],
       [9.]])

### Mathematical functions

The sum of elements of a vector:

In [100]:
x_=np.array([[1],[2],[3],[4]])
np.sum(x_)

10

or

In [101]:
x_.sum()

10

The product of elements of a vector:

In [102]:
np.prod(x_)

24

or

In [103]:
x_.prod()

24

The cumulative sum as a sequence of partial sums of a given vector (result is an array). 

In [104]:
np.cumsum(x_)

array([ 1,  3,  6, 10], dtype=int32)

The cumulative product as a sequence of partial products of a given vector (result is an array). 

In [105]:
np.cumprod(x_)

array([ 1,  2,  6, 24], dtype=int32)

The power to $p$ of a vector $\mathbf{x}$ is denoted by $\mathbf{x}^p$ and represents element-wise operation (all the elements of the vector are raised to the power of $p$).

In [106]:
p=2
x_**p

array([[ 1],
       [ 4],
       [ 9],
       [16]], dtype=int32)

In [107]:
np.power(x_,p)

array([[ 1],
       [ 4],
       [ 9],
       [16]], dtype=int32)

Square of a vector:

In [108]:
np.square(x_)

array([[ 1],
       [ 4],
       [ 9],
       [16]], dtype=int32)

Square-root of a vector:

In [109]:
np.sqrt(x_)

array([[1.        ],
       [1.41421356],
       [1.73205081],
       [2.        ]])

With $N$ number of observations and another $N$ number of estimations the residual sum of squares (or the Euclidean distance between two $N$ dimensional vectors) is given with the formula (vectorized form also provided):<br>
$\sqrt{\sum_{i=1}^{N}{(x_i-y_i)^2}}=\sqrt{\mathrm{\Sigma}(\mathbf{x}-\mathbf{y})^2}$

In [110]:
y_=np.arange(5,9)[:,np.newaxis]
np.sqrt(np.sum((x_-y_)**2))

8.0

We can also calculate the slope of the regression line using the equation:<br>
$w=\frac{\mathrm{\Sigma}((\mathbf{y}-\overline y)\circ(\mathbf{x}-\overline x))}{\mathrm{\Sigma}(\mathbf{x}-\overline x)^2}$ <br>
and the corresponding NumPy code:

In [111]:
np.sum((y_-y_.mean())*(x_-x_.mean()))/np.sum((x_-x_.mean())**2)

1.0

The absolute value of the difference between the two vectors is:

In [112]:
np.abs(x_-y_)

array([[4],
       [4],
       [4],
       [4]])

In time series analysis you may need to compute the difference between the current and previous value in an array containing time series data.

In [113]:
np.ediff1d(x_)

array([1, 1, 1])

Functions like, natural exponent are also define element-wise.

In [114]:
np.exp(x_)

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692],
       [54.59815003]])

The same is true for the and natural logarithm.

In [115]:
np.log(y_)

array([[1.60943791],
       [1.79175947],
       [1.94591015],
       [2.07944154]])

### Statistical functions

The mean of a sample is:<br>
$\overline{x}=\frac{1}{N}\sum_{i=1}^N x^{(i)}==\frac{1}{N}\Sigma\mathbf x$<br>
which translates to NumPy as:

In [116]:
N=len(x_)
1/N*np.sum(x_)

2.5

But we can use the *mean* function:

In [117]:
np.mean(x_)

2.5

or

In [118]:
x_.mean()

2.5

The median of the sample is:

In [119]:
np.median(x_)

2.5

The biased variance can be either calculated with formula:<br>
$\sigma^2=\frac{1}{N}\sum_{i=1}^{N}(x_i-\overline x)^2=\frac{1}{N}\mathrm{\Sigma}(\mathbf{x}-\overline x)^2$<br>
which in NumPy translates to:

In [120]:
N,_=x_.shape
1/N*np.sum((x_-x_.mean())**2)

1.25

or by using the appropriate method:

In [121]:
x_.var(ddof=0)

1.25

The unbiased standard deviation is:

In [122]:
x_.std(ddof=1)

1.2909944487358056

The sample correlation coefficient is defined as:<br>
$r_{xy}=\frac{\sum_{i=1}^{N}(x^{(i)}-\overline x)(y^{(i)}-\overline y)}{\sqrt{\sum_{i=1}^{N}(x^{(i)}-\overline x)^2}\sqrt{\sum_{i=1}^{N}(y^{(i)}-\overline y)^2}}$<br>
which in NumPy is a single line of code:

In [123]:
np.sum((x_-x_.mean())*(y_-y_.mean()))/(np.sqrt(np.sum((x_-x_.mean())**2))*np.sqrt(np.sum((y_-y_.mean())**2)))

0.9999999999999998

or using the *corrcoeff* method:

In [124]:
np.corrcoef(x_,y_,rowvar=False)

array([[1., 1.],
       [1., 1.]])

The 50% percentile can be obtained with the *percentile* method:

In [125]:
np.percentile(x_,50)

2.5

The first quartile, i.e. 0.25 quantile, can be obtained with the *quantile* method:

In [126]:
np.quantile(x_,0.25)

1.75

The minimum and maximum element of a NumPy ndarray with one dimension (or ndarray with two dimension but with second axis equal to 1) can be obtained with Python *min* and *max* methods.

In [127]:
np.min(x_)

1

or

In [128]:
x_.min()

1

respetive

In [129]:
np.max(x_)

4

or

In [130]:
x_.max()

4

We can also find the index of a vector element being the minimum or maximum value.

In [131]:
np.argmin(x_)

0

respective

In [132]:
np.argmax(x_)

3

### Vector Dot Product

The inner product of two vectors is equivalent with the sum of products of two equal-length sequences of numbers, or to the sum of squares of a sequence of numbers.

With NumPy *dot* method:

In [133]:
x_=np.array([1,2,3],ndmin=2).T
y_=np.array([4,5,6],ndmin=2).T
np.dot(x_.T,y_)

array([[32]])

With ndarray *dot* method:

In [134]:
x_.T.dot(y_)

array([[32]])

Using the NumPy *inner* method:

In [135]:
np.inner(x_[:,0],y_[:,0])

32

With '@' operator (preferred to resemble the mathematical formulas).

In [136]:
x_.T@y_

array([[32]])

Castig to int the inner product of the two vectors:

In [137]:
int(x_.T@y_)

32

Casting to int the inner product of the vector with itself:

In [138]:
int(x_.T@x_)

14

The outer product of two column vectors with $N$ and $M$ elements, respectively, is a matrix with $N\times M$ elements (in case of outer product the two vectors can have different number of elements).

In [139]:
x_=np.array([1,2,3,4],ndmin=2).T
y_=np.array([7,8,9],ndmin=2).T
x_@y_.T

array([[ 7,  8,  9],
       [14, 16, 18],
       [21, 24, 27],
       [28, 32, 36]])

If we were to use ndarrays with rank 1 for vectors then there would be no difference between the following operations, as all provides the same result.

In [140]:
x1_=np.array([1,2,3,4])
y1_=np.array([5,6,7,8])
x1_@y1_

70

In [141]:
x1_.T@y1_

70

In [142]:
x1_@y1_.T

70

In [143]:
np.inner(x1_,y1_)

70

### Sorting and Searching

Sometimes you may want to sort the vector elements (NumPy array).

Sorting random integer values in ascending order:

In [144]:
np.random.seed(46)
x_=np.random.randint(1,10,5)[:,np.newaxis]
np.sort(x_,axis=0)

array([[3],
       [4],
       [5],
       [6],
       [9]])

You may have sorted in descending order if you use slicing with reverse order selection:

In [145]:
np.sort(x_,axis=0)[::-1]

array([[9],
       [6],
       [5],
       [4],
       [3]])

Sorting is done on a copy, so x_ is not altered.

In [146]:
x_

array([[6],
       [9],
       [5],
       [4],
       [3]])

You may perform an indirect sort along the given axis and return only the indexes.

In [147]:
np.argsort(x_,axis=0)

array([[4],
       [3],
       [2],
       [0],
       [1]], dtype=int64)

In [148]:
x_[np.argsort(x_[:,0])]

array([[3],
       [4],
       [5],
       [6],
       [9]])

You may want to know the non-zero elements of an array.

In [149]:
np.nonzero(x_)

(array([0, 1, 2, 3, 4], dtype=int64), array([0, 0, 0, 0, 0], dtype=int64))

This is useful when applied to a Boolean array of a condition (like which elements are greater than or equal ton 3). We are interested only in the first axis.

In [150]:
np.nonzero(x_[:,0]>=5)

(array([0, 1, 2], dtype=int64),)

You may count the number of non-zero elements with *count-nonzero* method:

In [151]:
np.count_nonzero(x_)

5

We can select only those elements that are greater than or equal to 5.

In [152]:
np.where(x_[:,0]>=5)

(array([0, 1, 2], dtype=int64),)

Or we can select elements from two vectors (arrays) depending which one is greater.

In [153]:
y_=np.array([[1],[2],[3],[4],[5]])
np.where(x_>y_,x_,y_)

array([[6],
       [9],
       [5],
       [4],
       [5]])

Find the indices of array elements that are non-zero using the *argwhere* method.

In [154]:
np.argwhere(y_)

array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0]], dtype=int64)

You can check if a given element is contained in an array.

In [155]:
np.isin(y_,2)

array([[False],
       [ True],
       [False],
       [False],
       [False]])

You can check if a sequence of elements are contained in an array.

In [156]:
np.isin(y_,[2,4])

array([[False],
       [ True],
       [False],
       [ True],
       [False]])

Or even can be tested if elements of an array are contained in the other array.

In [157]:
np.isin(y_,x_)

array([[False],
       [False],
       [ True],
       [ True],
       [ True]])

Find the unique elements of x as a vector of 9,9,5,4,3:

In [158]:
x_[0,0]=9
np.unique(x_)

array([3, 4, 5, 9])

Find unique elements with the indexes of the array where the unique elements found (only first occurrence provided):

In [159]:
np.unique(x_,return_index=True)

(array([3, 4, 5, 9]), array([4, 3, 2, 0], dtype=int64))

Find unique elements with indexes to reconstruct the original array.

In [160]:
np.unique(x_,return_inverse=True)

(array([3, 4, 5, 9]), array([3, 3, 2, 1, 0], dtype=int64))

Find unique elements with the number of occurrences.

In [161]:
np.unique(x_,return_counts=True)

(array([3, 4, 5, 9]), array([1, 1, 1, 2], dtype=int64))

## 4. Matrices <a name="Matrices"></a>

A matrix (denoted with bold capital letters in the book, like $\mathbf A, \mathbf B, \mathbf C, ... \mathbf X,\mathbf Y,\mathbf Z,...$) is represented by a rank 2 ndarray in NumPy. The first axis always represents the number of rows, while the second axis the number of columns. 

### Matrix Initialization

Matrices can be initialized with nested lists or nested tuples:

In [162]:
X=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]],float)
X

array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.],
       [7., 8., 9.]])

You can check the dimension of the array

In [163]:
X.ndim

2

respective its shape

In [164]:
X.shape

(4, 3)

We can also create a matrix initialized with all zeros or all ones using the \texttt{zeros} methods. The shape of the matrix shall be also provided in the format of a tuple with two elements, the first representing the number of rows, the second the number of columns:

In [165]:
Y=np.zeros((2,3))
Y

array([[0., 0., 0.],
       [0., 0., 0.]])

Similarly you can use the *ones* method

In [166]:
Z=np.ones((4,3))
Z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

or the *full* method:

In [167]:
Z=np.full((2, 3), 5.25)
Z

array([[5.25, 5.25, 5.25],
       [5.25, 5.25, 5.25]])

The identity matrix can be also easily created with the \texttt{identity} method providing a single number for the squared matrix:

In [168]:
I=np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

That can be generalized for any shape of matrix and any diagonal of the matrix with \texttt{eye} method. We need to provide the number of rows, the number of columns, and the number of diagonal to be set to 1 (the main diagonal is 0 (default value), a positive value refers to an upper diagonal, and a negative value to a lower diagonal).

The following is identical with *identity(2)* method.

In [169]:
Z=np.eye(2,2)
Z

array([[1., 0.],
       [0., 1.]])

Number of off-diagonal is +2:

In [170]:
Z=np.eye(3,4,2)
Z

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

Number of diagonal is -2:

In [171]:
Z=np.eye(5,3,-2)
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

That can be even more generalized by using the *tri* method, which provides an array with ones at and below the given diagonal and zeros elsewhere.

For positive off-diagonal value:

In [172]:
Z=np.tri(3,4,1)
Z

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

For negativ off-diagonal value

In [173]:
Z=np.tri(3, 5, -1)
Z

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Upper and lower triangular matrices can be created with *triu*

In [174]:
np.triu((2,2))

array([[2, 2],
       [0, 2]])

respective with *tril*

In [175]:
np.tril(((2,1,0),(3,2,1),(4,3,2)),-1)

array([[0, 0, 0],
       [3, 0, 0],
       [4, 3, 0]])

With the *diag* method, a diagonal matrix can be created from a sequence of numbers (or a 1-dimensional array).

In [176]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

When creating the 3D plot of a function, you may need a mesh grid of plane coordinates to evaluate your function during plotting for all these points.

In [177]:
x_=np.linspace(1,4,4)
y_=np.linspace(1,4,4)
np.meshgrid(x_,y_)

[array([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]]),
 array([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]])]

You can also initialize a matrix with random values using the \texttt{random} submodul of NumPy.

In [178]:
np.random.seed(10)
Z=np.random.rand(3,2)
Z

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665]])

Another popular initialization method is *multivariate_normal*, which returns a sample (or samples) from a multivariate normal distribution. For example, for random samples from a distribution $\mathcal N(\mu, \Sigma)$, you should use:

In [179]:
np.random.seed(10)
mu=[0,0]
Sigma=[[1,0],[0,1]]
np.random.multivariate_normal(mu,Sigma)

array([1.3315865 , 0.71527897])

for one sample, respective the following code for three samples.

In [180]:
np.random.seed(10)
Z=np.random.multivariate_normal(mu,Sigma,3)
Z

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556]])

### Accessing Matrix Elements

As an example, let's take the previously obtained matrix as three random samples from the multivariate normal distribution.

Accessing 1st element of 1st row:

In [181]:
Z[0,0]

1.331586504129518

Accessing last element of the 2nd row:

In [182]:
Z[1,-1]

-0.008383849928522256

Accessing the last column in reverse order:

In [183]:
Z[::-1,-1]

array([-0.72008556, -0.00838385,  0.71527897])

Here are some more exmaples, for fancy indexing.

In [184]:
X=np.arange(1,37,1).reshape(6,6)
X

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

Selecting first column (green color in the book):

In [185]:
X[:,0]

array([ 1,  7, 13, 19, 25, 31])

Selecting 3rd and 6th element from the first and third row (red color in the book):

In [186]:
X[:4:2,2:7:3]

array([[ 3,  6],
       [15, 18]])

Selecting the 2nd, 3rd, and 4th element from 4th row (ligh blue color in the book):

In [187]:
X[3,1:4]

array([20, 21, 22])

Select the last two elements from hte 3rd and 4th column (dark blue in the book):

In [188]:
X[4:,2:4]

array([[27, 28],
       [33, 34]])

Selecting the off-diagonal elements above the main diagonal (yellow color in the book):

In [189]:
X[[0,1,2,3,4],[1,2,3,4,5]]

array([ 2,  9, 16, 23, 30])

Selecting the 2nd and 4th row (blue rectangles in the book)

In [190]:
X[1:4:2,:]

array([[ 7,  8,  9, 10, 11, 12],
       [19, 20, 21, 22, 23, 24]])

Selecting the last two elements from the 2nd, 4th and last column (red rectangles in the book):

In [191]:
X[[-2,-1],1::2]

array([[26, 28, 30],
       [32, 34, 36]])

Selecting from the 2nd and 5th column the 2nd, 3rd, and the last element (pink color in the book):

In [192]:
mask=np.array([0,1,1,0,0,1], dtype=bool)
X[mask,1::3]

array([[ 8, 11],
       [14, 17],
       [32, 35]])

### Operations on Matrices

Transpose of a matrix:

In [193]:
Z.T

array([[ 1.3315865 , -1.54540029,  0.62133597],
       [ 0.71527897, -0.00838385, -0.72008556]])

Matrix addition to scalar made through broadcast of the scalar.
The following is made on the copy of X.

In [194]:
X=np.array([[1,2,3],[4,5,6]])
X+x

array([[ 6,  7,  8],
       [ 9, 10, 11]])

as can be checked by printing out X:

In [195]:
X

array([[1, 2, 3],
       [4, 5, 6]])

The addition is done in-place:

In [196]:
X+=x
X

array([[ 6,  7,  8],
       [ 9, 10, 11]])

Sum of all elements of the matrix:

In [197]:
X=np.array([[1,2,3],[4,5,6]])
np.sum(X)

21

Sum of elements of each row (the result is a row vector):

In [198]:
np.sum(X,axis=0,keepdims=True)

array([[5, 7, 9]])

Sum of elements of each column (the result is a column vector):

In [199]:
np.sum(X,axis=1,keepdims=True)

array([[ 6],
       [15]])

With matrices you can also calculate the product of all elements.

In [200]:
np.prod(X)

720

But, in case of matrices we can also define the product of each row,

In [201]:
np.prod(X,axis=0,keepdims=True)

array([[ 4, 10, 18]])

respective the prodcut of each column:

In [202]:
np.prod(X,axis=1,keepdims=True)

array([[  6],
       [120]])

You can calculate the mean of $N$ observations for the $D$ features.

In [203]:
N,_=X.shape
mu_=1/N*np.sum(X,axis=0,keepdims=True)
mu_

array([[2.5, 3.5, 4.5]])

This can be also obtained with *mean* method. With matrices you can either calculate the mean of the entire matrix or the mean of either the rows or columns. 

In [204]:
X.mean()

3.5

In [205]:
mu_=X.mean(axis=0,keepdims=True).T
mu_

array([[2.5],
       [3.5],
       [4.5]])

In case the operation is performed between a matrix and the vector, the same broadcasting rule will be applied as between a matrix and scalar. But, for the broadcasting to be successfully performed, the vector shall have the appropriate shape. For example, centering the data is as simple as:

In [206]:
Xo=X-mu_.T
Xo

array([[-1.5, -1.5, -1.5],
       [ 1.5,  1.5,  1.5]])

Standard deviation vector defined as:<br>
$\sigma=\sqrt{\frac{1}{N-1}\Big(\sum_c (\mathbf X-\mu^\top)^2\Big)^\top}$<br>
which translates to NumPy:

In [207]:
sigma_=np.sqrt(1/(N-1)*np.sum((X-mu_.T)**2,axis=0,keepdims=True)).T
sigma_

array([[2.12132034],
       [2.12132034],
       [2.12132034]])

or

In [208]:
sigma_=np.std(Xo,ddof=1,axis=0,keepdims=True).T
sigma_

array([[2.12132034],
       [2.12132034],
       [2.12132034]])

Standardize data:

In [209]:
Xs=Xo/sigma_.T
Xs

array([[-0.70710678, -0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678,  0.70710678]])

Some classifiers might need the indicator function. Let's take a simple example with 3 classes

In [210]:
classes=np.array(['low','medium','high'])[np.newaxis]
classes

array([['low', 'medium', 'high']], dtype='<U6')

and 6 labels (output of 6 observations):

In [211]:
y_=np.array(['medium','high','low','medium','medium','low'])[:,np.newaxis]
y_

array([['medium'],
       ['high'],
       ['low'],
       ['medium'],
       ['medium'],
       ['low']], dtype='<U6')

the indicator function can be calculated as follows:

In [212]:
(y_==classes).astype(int)

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

### Matrix Dot Product

The (biased) sample covariance matrix can be easily calculated with the formula:<br>
$\mathbf S=\frac{1}{(N-1)}(\mathbf X-\mu^\top)^\top(\mathbf X-\mu^\top)$<br>
which translates to NumPy as:

In [213]:
S=1/(N-1)*(X-mu_.T).T@(X-mu_.T)
S

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

The sample covariance matrix can be also calculated with *cov* and the sample correlation matrix with *corrcoef* method:

In [214]:
S=np.cov(X,rowvar=False)
S

array([[4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5],
       [4.5, 4.5, 4.5]])

The correlation matrix is:

In [215]:
R=np.corrcoef(X,rowvar=False)
R

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

If the input is standardized, the covariance matrix is equalt to the correlation matrix.

Thus, we can calculate the correlation matrix with formula:<br>
$\mathbf R=\frac{1}{N-1}\mathbf X_\star^\top\mathbf X_\star$<br>
where $\mathbf X_\star$ represents the standardized data.

In [216]:
1/(N-1)*Xs.T@Xs

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

or use the *cov* method:

In [217]:
np.cov(Xs,rowvar=False)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

The correlation matrix can be calculated from the covariance matrix and standard deviation vector with formula:<br>
$\mathbf R= \frac{\Sigma}{\sigma\cdot\sigma^\top}$

In [218]:
S/(sigma_@sigma_.T)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

When a $D\times 1$ vector is multiplies from the left with a matrix $N\times D$ the result will be a new vector $D\times 1$. Mathematically $\mathbf z=\mathbf X \cdot \mathbf x$. For example, in the following code vector with coordinates [1,1] will be rotated by 180 degrees..

In [219]:
Z=np.array([[-1,0,0],[0,-1,0],[0,0,-1]])
x_=np.array([1,1,1])[:,np.newaxis]
Z@x_

array([[-1],
       [-1],
       [-1]])

We may also define a dot product between a row vector and a matrix, but the dimensions need to be matched.

In [220]:
x_.T@Z.T

array([[-1, -1, -1]])

### Linear algebra

The diagonal of the matrix can be obtained with the *diag* method:

In [221]:
np.diag(Z)

array([-1, -1, -1])

while the trace of the matrix with *trace* method:

In [222]:
np.trace(Z)

-3

The diagonal below the main:

In [223]:
np.diag(Z,k=-1)

array([0, 0])

The determinant, respective the inverse of a matrix can be obtained using the submodule linalg.
Determinant of the rotation matrix:

In [224]:
from numpy.linalg import det
det(Z)

-1.0

Inverse of the rotation matrix:

In [225]:
from numpy.linalg import inv
inv(Z)

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.]])

The rank of the rotation matrix:

In [226]:
from numpy.linalg import matrix_rank, cond
matrix_rank(Z)

3

Condition number of a matrix:

In [227]:
cond(Z)

1.0

The spectral decomposition of the rotation matrix:

In [228]:
from numpy.linalg import eig
eig(Z)

(array([-1., -1., -1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

Singular value decomposition (SVD) as a generalization of eigendecomposition for any rectangular matrix.

In [229]:
from numpy.linalg import svd
svd(X) 

(array([[-0.3863177 ,  0.92236578],
        [-0.92236578, -0.3863177 ]]),
 array([9.508032  , 0.77286964]),
 array([[-0.42866713, -0.56630692, -0.7039467 ],
        [-0.80596391, -0.11238241,  0.58119908],
        [ 0.40824829, -0.81649658,  0.40824829]]))

## 5. Array Manipulations <a name="Array"></a>

Let's check the shape of the matrix X defined earlier:

In [230]:
X.shape

(2, 3)

Reshape without changing the content.

In [231]:
np.reshape(X,(1,6))

array([[1, 2, 3, 4, 5, 6]])

Resize to a greater matrix (the remaining part will be filled with repeated values of the X matrix.

In [232]:
np.resize(X,(2,5))

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4]])

Resize to a smaller matrix (the last values not fitting will be discarded).

In [233]:
np.resize(X,(2,2))

array([[1, 2],
       [3, 4]])

In [234]:
np.ravel(X)

array([1, 2, 3, 4, 5, 6])

In [235]:
X.flatten()

array([1, 2, 3, 4, 5, 6])

In [236]:
np.moveaxis(X,0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [237]:
np.swapaxes(X,0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

<img src = "images/AML1-Cover.png" width = 110, align = "left" style="margin:0px 20px">

<span style="color:blue">**Note:**</span> This Jupyter Notebook is accompanying the book: <br> $\qquad$ <b>Advanced Machine Learning Made Easy</b> <br> $\qquad$ From Theory to Practice with NumPy and scikit-learn <br> $\qquad$ <i> Volume 1: Generalized Linear Models</i><br>
by Ferenc Farkas, Ph.D. 

If you find this Notebook useful, please support me by buying the book at [Leanpub](http://leanpub.com/AML1). <br>
Copyright notice: This Jupyter Notebook is made available under the [MIT License](https://opensource.org/licenses/MIT).